#! /bin/sh

[ "$(xrandr | grep -c " connected")" = 1 ] &&
    bspc monitor -d I II III IV V VI VII VIII IX X ||
        bspc monitor eDP1 -d 1 2 3 4 5 && bspc monitor HDMI2 -d 6 7 8 9 10

bspc config border_width          1
#bspc config focused_border_color  "#1d2021"
bspc config focused_border_color  "32302f"
bspc config normal_border_color   "1d2021"
# bspc config window_gap            0
bspc config top_padding           25
bspc config top_monocle_padding   0
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a KeepassXC state=floating
bspc rule -a Brave manage=off

killall -w sxhkd picom &
sleep 0.1
sxhkd -m -1
picom
